name: Node CI/CD Pipeline with Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Auto-fix with ESLint
        run: npx eslint . --fix

      - name: Run Tests
        run: npm test

      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  notify:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Notify Slack of Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ CI/CD success! Node app deployed to Render 🚀"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack of Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ CI/CD FAILED! Something broke in the pipeline 😓"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
